name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]
        pnpm-version: [10]
        registry-url: [https://npm.pkg.github.com/]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: ${{ matrix.node-version }}
          pnpm-version: ${{ matrix.pnpm-version }}
          registry-url: ${{ matrix.registry-url }}
      - name: Run tests
        run: pnpm run test